---
manufacturer: DirectOut
model: PRODIGY.MC
slug: directout-prodigy-mc
u_height: 2.0
is_full_depth: true
airflow: left-to-right
weight: 10
weight_unit: kg
power-ports:
  - name: PSU 1
    type: iec-60320-c14
  - name: PSU 2
    type: iec-60320-c14
interfaces:
  - name: MGMT
    type: 1000base-t
    mgmt_only: true
  - name: GPIO
    type: other
    description: 9 pin D-sub
  - name: WordClock 1 In
    type: other
  - name: WordClock 1 out
    type: other
  - name: WordClock 2 / Video In
    type: other
  - name: WordClock 2 / Video out
    type: other
module-bays:
  - name: Audio network slot
  - name: MADI 1
    position: MADI 1
  - name: MADI 2
    position: MADI 2
  - name: Slot 1
    position: '1'
  - name: Slot 2
    position: '2'
  - name: Slot 3
    position: '3'
  - name: Slot 4
    position: '4'
  - name: Slot 5
    position: '5'
  - name: Slot 6
    position: '6'
  - name: Slot 7
    position: '7'
  - name: Slot 8
    position: '8'
