---
manufacturer: DirectOut
model: PRODIGY.MP
slug: directout-prodigy-mp
u_height: 2.0
is_full_depth: true
airflow: left-to-right
weight: 10
weight_unit: kg
power-ports:
  - name: PSU 1
    type: iec-60320-c14
  - name: PSU 2
    type: iec-60320-c14
interfaces:
  - name: MANAGEMENT 1
    type: 1000base-t
    mgmt_only: true
  - name: MANAGEMENT 2
    type: 1000base-t
    mgmt_only: true
  - name: MANAGEMENT 3
    type: 1000base-x-sfp
    mgmt_only: true
rear-ports:
  - name: GPIO
    type: other
    positions: 1
    description: 9 pin D-sub
  - name: WordClock 1 In
    type: bnc
  - name: WordClock 1 out
    type: bnc
  - name: WordClock 2 / Video In
    type: bnc
  - name: WordClock 2 / Video out
    type: bnc
  - name: MIDI in
    type: other
    description: DIN
  - name: MIDI out
    type: other
    description: DIN
module-bays:
  - name: MADI 1
  - name: MADI 2
  - name: Audio network 1
  - name: Audio network 2
  - name: Slot 1
    position: '1'
  - name: Slot 2
    position: '2'
  - name: Slot 3
    position: '3'
  - name: Slot 4
    position: '4'
